apiVersion: v1
kind: Service
metadata:
  name:  halb-nginx
spec:
  selector:
    app: halb-nginx

  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP #optional protocol

