version: '3.9'
volumes:
  goat-db-data: null
networks:
  traefik-proxy:
    external: true
services:
  blog-halb:
    image: ghcr.io/robalb/my-website:sha-67ffee29b382ffb61883579b3216016bd69f5fb8
    restart: unless-stopped
    expose:
      - '80'
    labels:
      - traefik.enable=true
      - traefik.http.routers.blog-halb.rule=Host(`halb.it`)
      - traefik.http.routers.blog-halb.entrypoints=websecure
      - traefik.http.routers.blog-halb.tls=true
      - traefik.http.routers.blog-halb.tls.certresolver=myresolver
    networks:
      - traefik-proxy
  goat:
    image: baethon/goatcounter:2.0
    restart: unless-stopped
    expose:
      - '8080'
    environment:
      GOATCOUNTER_DOMAIN: analytics.halb.it
      GOATCOUNTER_EMAIL: ${GOAT_EMAIL}
      GOATCOUNTER_PASSWORD: ${GOAT_PASSWORD}
    labels:
      - traefik.enable=true
      - traefik.http.routers.goat.rule=Host(`analytics.halb.it`)
      - traefik.http.routers.goat.entrypoints=websecure
      - traefik.http.routers.goat.tls=true
      - traefik.http.routers.goat.tls.certresolver=myresolver
    networks:
      - traefik-proxy
    volumes:
      - goat-db-data:/goatcounter/db
