name: Build and deploy blog
on:
  push:
    branches:
      - master
    paths:
      - 'astro-website/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # https://github.com/docker/metadata-action#typesha
          tags: |
            type=sha,priority=100,format=short,prefix=sha-
            type=raw,priority=200,prefix=sha-,value=${{ github.sha }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: update image tags in k8s manifests
        uses: fjogeleit/yaml-update-action@v0.16.0
        with:
          valueFile: 'k8s/deployment.yaml'
          propertyPath: 'spec.template.spec.containers[0].image'
          value: ghcr.io/robalb/my-website:sha-${{ github.sha }}
          updateFile: true
          commitChange: false

      - name: update image tags in compose-prod
        uses: fjogeleit/yaml-update-action@v0.16.0
        with:
          valueFile: 'compose-prod/blog-halb/docker-compose.yml'
          propertyPath: "services['blog-halb'].image"
          value: ghcr.io/robalb/my-website:sha-${{ github.sha }}
          updateFile: true
          commitChange: false

      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -am "Updated image tags in the app manifests"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
           branch: ${{ github.ref }}
